name: Image Builder for Akamai Development and Build Images
# Description: This workflow will lint and build and deploy a Docker image.  
# For merges to main it will push the image to the GitHub registry attached to this repo.
# The image may be used in CI and locally in devcontainer. 

# The workflow is only run when changes are made to the dockerfile.  It will not run for other changes.
on:
  pull_request:
    branches:
      - main
    paths:
      - "development.Dockerfile"
  push:
    branches:
      - main
    paths:
      - "development.Dockerfile"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: development.Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # See here for docs on pushing images to github packages: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./development.Dockerfile
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ghcr.io/${{ github.repository }}:dev-build